### ISSUE TITLE
Customized Icon for the app

### ISSUE THREAD

**Issue by fernandopiniani** [fernandopiniani/cyrillic-pomodoro#2]
I need a any app logo to update the following files:

- /public/logo192.png [PNG]
- /public/logo512.png [PNG]
- /public/favicon.ico [ICO]
- /src/logo.svg [SVG]

I would like it to have some related with russian.

**Comment by DevCoder10** [comment]
what kind of icon do you need? rusisian famous thing?

**Comment by iamprakash13** [comment]
what kind of icon you need? russian things

**Comment by douglasevaristo** [comment]
Hi, i can help ok?

**Comment by douglasevaristo** [comment]
Done :) What do you think?
