### ISSUE TITLE
Visual progression bar for timer component.

### ISSUE THREAD

**Issue by fernandopiniani** [fernandopiniani/cyrillic-pomodoro#4]
I would like to add this component https://www.npmjs.com/package/react-circular-progressbar around the timer with the following checklist 

- [x] Reflects `timeLeft` state. Full bar (colorful) means the timer has started to count (e.g. 25 minutes left), empty bar (grey) times has ended (e.g. 0 minutes left).
- [x] Animation is working.

**Comment by muresan-raul** [comment]
Hello, I made a PR for this here https://github.com/fernandopiniani/cyrillic-pomodoro/pull/5
